# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Resource import Myqrc_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1574, 866)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
#         MainWindow.setStyleSheet("QMainWindow{\n"
# "    background-image:url(\"D:\\我的桌面\\b站自学\\pythonProject2\\Resource\\Pic\\v2-12c09440b7049d539b5e9cd86665d48a_1440w.jpg\")\n"
# "}\n"
# "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Pic_frame = QtWidgets.QFrame(self.centralwidget)
        self.Pic_frame.setGeometry(QtCore.QRect(570, 150, 501, 571))
        self.Pic_frame.setStyleSheet("QPushButton { border: 2px solid black; }")
        self.Pic_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pic_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pic_frame.setLineWidth(-1)
        self.Pic_frame.setObjectName("Pic_frame")
        self.PIC_Show = QtWidgets.QLabel(self.Pic_frame)
        self.PIC_Show.setEnabled(True)
        self.PIC_Show.setGeometry(QtCore.QRect(10, 210, 480, 360))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PIC_Show.sizePolicy().hasHeightForWidth())
        self.PIC_Show.setSizePolicy(sizePolicy)
        self.PIC_Show.setStyleSheet("QLabel {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.PIC_Show.setText("")
        self.PIC_Show.setPixmap(QtGui.QPixmap(":/path/Pic/伞-小车.png"))
        self.PIC_Show.setAlignment(QtCore.Qt.AlignCenter)
        self.PIC_Show.setObjectName("PIC_Show")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Pic_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 461, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_pic = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_pic.setStyleSheet("QPushButton {\n"
"    background-color: #5DA5DA;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #1B4F72;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1B4F72;\n"
"    border-color: #5DA5DA;\n"
"    cursor: pointer;\n"
"}\n"
"")
        self.save_pic.setObjectName("save_pic")
        self.horizontalLayout.addWidget(self.save_pic)
        self.btn_suspend = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_suspend.setStyleSheet("QPushButton {\n"
"    background-color: #5DA5DA;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #1B4F72;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1B4F72;\n"
"    border-color: #5DA5DA;\n"
"    cursor: pointer;\n"
"}\n"
"")
        self.btn_suspend.setObjectName("btn_suspend")
        self.horizontalLayout.addWidget(self.btn_suspend)
        self.Low_crl_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Low_crl_Frame.setGeometry(QtCore.QRect(1200, 80, 311, 411))
        self.Low_crl_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Low_crl_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Low_crl_Frame.setObjectName("Low_crl_Frame")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.Low_crl_Frame)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(270, 30, 20, 361))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.layoutWidget = QtWidgets.QWidget(self.Low_crl_Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 258, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.order_low = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.order_low.sizePolicy().hasHeightForWidth())
        self.order_low.setSizePolicy(sizePolicy)
        self.order_low.setTextFormat(QtCore.Qt.AutoText)
        self.order_low.setScaledContents(False)
        self.order_low.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.order_low.setObjectName("order_low")
        self.verticalLayout.addWidget(self.order_low)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.UDP_frame = QtWidgets.QFrame(self.centralwidget)
        self.UDP_frame.setGeometry(QtCore.QRect(140, 80, 371, 601))
        self.UDP_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.UDP_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.UDP_frame.setLineWidth(3)
        self.UDP_frame.setObjectName("UDP_frame")
        self.Run_model = QtWidgets.QPushButton(self.UDP_frame)
        self.Run_model.setGeometry(QtCore.QRect(70, 510, 171, 51))
        self.Run_model.setObjectName("Run_model")
        self.UDP_send = QtWidgets.QLabel(self.UDP_frame)
        self.UDP_send.setGeometry(QtCore.QRect(15, 440, 61, 31))
        self.UDP_send.setObjectName("UDP_send")
        self.UDP_recieve = QtWidgets.QLabel(self.UDP_frame)
        self.UDP_recieve.setGeometry(QtCore.QRect(15, 170, 61, 91))
        self.UDP_recieve.setObjectName("UDP_recieve")
        self.mssg_rec = QtWidgets.QTextBrowser(self.UDP_frame)
        self.mssg_rec.setGeometry(QtCore.QRect(90, 104, 141, 210))
        self.mssg_rec.setMinimumSize(QtCore.QSize(109, 210))
        self.mssg_rec.setStyleSheet("QTextBrowser {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.mssg_rec.setMarkdown("")
        self.mssg_rec.setObjectName("mssg_rec")
        self.Upper_ipLB = QtWidgets.QLabel(self.UDP_frame)
        self.Upper_ipLB.setGeometry(QtCore.QRect(15, 70, 61, 31))
        self.Upper_ipLB.setObjectName("Upper_ipLB")
        self.mssg_sed = QtWidgets.QLineEdit(self.UDP_frame)
        self.mssg_sed.setGeometry(QtCore.QRect(90, 440, 141, 31))
        self.mssg_sed.setStyleSheet("QLineEdit\n"
" {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.mssg_sed.setObjectName("mssg_sed")
        self.Upper_ipEd = QtWidgets.QLineEdit(self.UDP_frame)
        self.Upper_ipEd.setGeometry(QtCore.QRect(90, 70, 141, 31))
        self.Upper_ipEd.setStyleSheet("QLineEdit\n"
" {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.Upper_ipEd.setText("")
        self.Upper_ipEd.setObjectName("Upper_ipEd")
        self.Lower_ipED = QtWidgets.QLabel(self.UDP_frame)
        self.Lower_ipED.setGeometry(QtCore.QRect(90, 360, 200, 31))
        self.Lower_ipED.setStyleSheet("QLabel {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.Lower_ipED.setText("")
        self.Lower_ipED.setObjectName("Lower_ipED")
        self.Lower_ipLB = QtWidgets.QLabel(self.UDP_frame)
        self.Lower_ipLB.setGeometry(QtCore.QRect(15, 360, 61, 31))
        self.Lower_ipLB.setMinimumSize(QtCore.QSize(1, 1))
        self.Lower_ipLB.setSizeIncrement(QtCore.QSize(3, 3))
        self.Lower_ipLB.setBaseSize(QtCore.QSize(3, 3))
        self.Lower_ipLB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lower_ipLB.setObjectName("Lower_ipLB")
        self.Sendmssg = QtWidgets.QPushButton(self.UDP_frame)
        self.Sendmssg.setGeometry(QtCore.QRect(240, 440, 41, 31))
        self.Sendmssg.setObjectName("Sendmssg")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1200, 570, 311, 161))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: white;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    color: rgb(16, 72, 255);  /* 修改标题的颜色为青绿色 */\n"
"    padding: 0 3px;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.dial = QtWidgets.QDial(self.groupBox)
        self.dial.setGeometry(QtCore.QRect(200, 40, 81, 81))
        self.dial.setStyleSheet("QDial {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 50%;\n"
"    color: #333;\n"
"    font-size: 14px;\n"
"    font-family: \"Microsoft Yahei\";\n"
"    padding: 10px;\n"
"    margin: 20px;\n"
"}\n"
"\n"
"")
        self.dial.setObjectName("dial")
        self.Right = QtWidgets.QPushButton(self.groupBox)
        self.Right.setGeometry(QtCore.QRect(130, 80, 51, 51))
        self.Right.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/path/Icon/caret-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Right.setIcon(icon)
        self.Right.setObjectName("Right")
        self.Left = QtWidgets.QPushButton(self.groupBox)
        self.Left.setGeometry(QtCore.QRect(30, 80, 51, 51))
        self.Left.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/path/Icon/caret-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Left.setIcon(icon1)
        self.Left.setObjectName("Left")
        self.Up = QtWidgets.QPushButton(self.groupBox)
        self.Up.setGeometry(QtCore.QRect(80, 30, 51, 51))
        self.Up.setStyleSheet("QPushBotton{\n"
"    background-image:url(:/path/Icon/caret-up.png);\n"
"}")
        self.Up.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/path/Icon/caret-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Up.setIcon(icon2)
        self.Up.setObjectName("Up")
        self.Down = QtWidgets.QPushButton(self.groupBox)
        self.Down.setGeometry(QtCore.QRect(80, 80, 51, 51))
        self.Down.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/path/Icon/caret-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Down.setIcon(icon3)
        self.Down.setObjectName("Down")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1700, 1000))
        self.background.setMaximumSize(QtCore.QSize(2000, 1000))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/path/Pic/img1.wallspic.com-chou_xiang_yi_shu-jian_yue-qi_fen-sheng_tai_qu-azure-3840x2160.jpg"))
        self.background.setScaledContents(True)
        self.background.setAlignment(QtCore.Qt.AlignCenter)
        self.background.setObjectName("background")
        self.background.raise_()
        self.Pic_frame.raise_()
        self.Low_crl_Frame.raise_()
        self.UDP_frame.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.save_pic, self.Upper_ipEd)
        MainWindow.setTabOrder(self.Upper_ipEd, self.mssg_sed)
        MainWindow.setTabOrder(self.mssg_sed, self.Run_model)
        MainWindow.setTabOrder(self.Run_model, self.btn_suspend)
        MainWindow.setTabOrder(self.btn_suspend, self.mssg_rec)
        MainWindow.setTabOrder(self.mssg_rec, self.Up)
        MainWindow.setTabOrder(self.Up, self.Left)
        MainWindow.setTabOrder(self.Left, self.Down)
        MainWindow.setTabOrder(self.Down, self.Right)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.save_pic.setText(_translate("MainWindow", "保存图片"))
        self.btn_suspend.setText(_translate("MainWindow", "停止播放"))
        self.order_low.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">下位机指令</p></body></html>"))
        self.Run_model.setText(_translate("MainWindow", "开始运行"))
        self.UDP_send.setText(_translate("MainWindow", "UDP发送"))
        self.UDP_recieve.setText(_translate("MainWindow", "UDP接收"))
        self.mssg_rec.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.mssg_rec.setPlaceholderText(_translate("MainWindow", "这里将会显示接受的信息"))
        self.Upper_ipLB.setText(_translate("MainWindow", "上位机IP"))
        self.mssg_sed.setPlaceholderText(_translate("MainWindow", "请输入信息"))
        self.Upper_ipEd.setPlaceholderText(_translate("MainWindow", "上位机IP"))
        self.Lower_ipLB.setText(_translate("MainWindow", "下位机IP"))
        self.Sendmssg.setText(_translate("MainWindow", "发送"))
        self.groupBox.setTitle(_translate("MainWindow", "下位机控制"))

